* +++<del>+++Add more book suggestions+++</del>+++ Unnecessary
* +++<del>+++Ask Monkeys for permission for their discord server link to be added+++</del>+++_Done_
* +++<del>+++Add more math articles (To be first queried from Matthew Bolan)+++</del>+++ _Done for now_
* Add more Computer Science( specifcally, Bit Manipulation) articles
* +++<del>+++Add write-ups for Modular Inverses , easy to understand intuitive articles on Lattices and why they are cool as such+++</del>+++ _Done_

* +++<del>+++**Add `relevant code` section and `reversal libs` section -> EarthComputer's Libseedfinding , KaptainWutax's things, LattiCG, Cubiomes , old stuff that was once considered to crack seeds**+++</del>+++ _Done_

* Considered - **Add relevant people section to name those who took up the work on cracking minecraft seeds. (KaptainWutax , Neil, EarthComputer, Matthew, Andrew, L64, Cortex, other folks from Minecraft@Home project as well)** : Probably will be dropped. 
* Considered - Add section for starting out with code for those who are very new to this

* +++<del>+++Add `tools` section for tools like MineMap , SeedCandy, SeedCracker, SASSA and other tools+++</del>+++ _Done_
* +++<del>+++Add Latice Reduction papers (LLL, BKZ discussion etc)+++</del>+++ _Done for now_
* +++<del>+++Add noob proofing+++</del>+++ _Done_


* _Over Ambitious Plan_ Considered : Deep dive into LattiCG code to see what it is doing and writeups based on that.
* Add section to find relevant code in the decompiled-mapped minecraft codebase


//Thank you to everyone who created such quality articles / worked on making seed reverse engineering possible !

---
= HEAVY WIP 
* Add terminology section for terms like -> phase, period, state, fuction call, attack, salts, structure, WorldSeed, LayerSeed, ChunkSeed, CarverSeed,offsets, basis etc  :  **Check terminlogy-wip.adoc if you can help**
* **Add topics on what Monkeys is researching(?)/looking for today i.e, modern seed cracking hunt and what it is about** : Pls help.


No copyright infringement intended.
